# NumPy Arrays

In [2]:
my_list = [1,2,3]

import numpy as np
arr = np.array(my_list)
arr

array([1, 2, 3])

In [4]:
marks = [[1,2,3],[4,5,6],[7,8,9]]
np.array(marks)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:

np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.linspace(0,5)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.random.rand(3)

array([0.93756091, 0.28065291, 0.28227556])

In [16]:
np.random.rand(3,3)

array([[0.78200326, 0.78030768, 0.19328049],
       [0.16984981, 0.09524947, 0.40441036],
       [0.23982374, 0.60792281, 0.22799178]])

In [17]:
np.random.randn(3)

array([-0.68902945,  0.42194991,  0.94462768])

In [18]:
np.random.randn(3,3)

array([[-1.49949653, -1.55642857,  0.1340475 ],
       [-1.05168968,  0.09894103,  0.1762509 ],
       [ 0.20889865, -0.54748748, -0.17679178]])

In [19]:
np.random.randint(1, 100) # with lowest exclusive and highest exclusive

62

In [20]:
np.random.randint(1, 100, 10)

array([53, 11, 51, 72, 92,  9, 62, 32, 83, 39])

In [22]:
arr = np.arange(25)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
ranarr = np.random.randint(1, 50, 10)

In [25]:
ranarr

array([44,  9, 26, 10,  4, 24, 46, 34, 37, 17])

In [26]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
ranarr.max()

46

In [28]:
ranarr.min()

4

In [29]:
ranarr.argmax() # Index value of the max element in the array

6

In [30]:
ranarr

array([44,  9, 26, 10,  4, 24, 46, 34, 37, 17])

In [31]:
ranarr.argmin()

4

In [32]:
arr = arr.reshape(5,5)

In [33]:
arr.shape

(5, 5)

# NumPy Indexing and Selection

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [7]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [8]:
arr[0:5] = 100

In [9]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
slice_of_arr = arr[0:6]

In [11]:
slice_of_arr

array([100, 100, 100, 100, 100,   5])

In [12]:
slice_of_arr[:]

array([100, 100, 100, 100, 100,   5])

In [13]:
slice_of_arr[:] = 99

In [14]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [15]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [16]:
arr_copy = arr.copy()

In [17]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [18]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [19]:
arr_copy[:] = 100

In [20]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [21]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [22]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [23]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [24]:
arr_2d[0][0]

5

In [25]:
arr_2d[2][1]

40

In [26]:
arr_2d[2,1]

40

In [27]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [29]:
arr_2d[1:2]

array([[20, 25, 30]])

In [30]:
arr_2d[:,0]

array([ 5, 20, 35])

In [31]:
arr = np.arange(0,11)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [34]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [35]:
arr_2d = np.arange(50).reshape(5,10)

In [36]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [37]:
arr_2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])

# NumPy Operations
- Array to Array
- Array to Scalars
- Universal Array Functions

In [38]:
# import numpy as np

arr = np.arange(11)

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [41]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [42]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [45]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [46]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [47]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [50]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [51]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [52]:
np.max(arr)

10

In [53]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [54]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

In [55]:
np.log(arr)

C:\Users\user\AppData\Local\Temp/ipykernel_5324/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])